development:
  access_key: '<your aws access key>'
  secret_access_key: '<your aws secret>'
  return_base: 'http://twittermentionmonitor.com'
  endpoint: 'https://fps.sandbox.amazonaws.com'
  pipeline: 'https://authorize.payments-sandbox.amazon.com/cobranded-ui/actions/start?'
  version: '2007-01-08'
